CREATE TABLE levels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title jsonb NOT NULL DEFAULT '{}'::jsonb,
  description jsonb NOT NULL DEFAULT '{}'::jsonb,
  difficulty smallint NOT NULL DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 5),
  sort_order integer NOT NULL UNIQUE CHECK (sort_order > 0),
  starting_board jsonb NOT NULL DEFAULT '{"rows": 20, "columns": 20, "cells": []}'::jsonb,
  target_board jsonb NOT NULL DEFAULT '{"rows": 20, "columns": 20, "cells": []}'::jsonb,
  starting_row integer NOT NULL DEFAULT 0,
  starting_column integer NOT NULL DEFAULT 0,
  validation_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX levels_published_sort_order_idx
  ON levels (sort_order)
  WHERE is_published;

INSERT INTO levels (
  id,
  slug,
  title,
  description,
  difficulty,
  sort_order,
  starting_board,
  target_board,
  starting_row,
  starting_column,
  validation_config,
  is_published
)
SELECT
  level_number,
  'level-' || level_number,
  jsonb_build_object('en', 'Level ' || level_number, 'es', 'Nivel ' || level_number),
  jsonb_build_object('en', 'Complete drawing challenge ' || level_number, 'es', 'Completa el reto de dibujo ' || level_number),
  CASE WHEN level_number <= 4 THEN 1 WHEN level_number <= 8 THEN 2 ELSE 3 END,
  level_number,
  jsonb_build_object('rows', 20, 'columns', 20, 'cells', jsonb_build_array()),
  jsonb_build_object(
    'rows', 20,
    'columns', 20,
    'cells', CASE level_number
      WHEN 1 THEN jsonb_build_array(jsonb_build_object('row', 0, 'column', 0, 'color', '#000000'))
      WHEN 2 THEN jsonb_build_array(jsonb_build_object('row', 0, 'column', 0, 'color', '#ff0000'), jsonb_build_object('row', 0, 'column', 1, 'color', '#ff0000'))
      WHEN 3 THEN jsonb_build_array(jsonb_build_object('row', 0, 'column', 0, 'color', '#0000ff'), jsonb_build_object('row', 1, 'column', 0, 'color', '#0000ff'))
      ELSE jsonb_build_array()
    END
  ),
  0,
  0,
  jsonb_build_object('type', 'drawing'),
  level_number <= 3
FROM generate_series(1, 12) AS level_number;

SELECT setval(
  pg_get_serial_sequence('levels', 'id'),
  (SELECT max(id) FROM levels)
);
