CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE CHECK (username = btrim(username) AND length(username) > 0),
  hashed_password text NOT NULL,
  role text NOT NULL DEFAULT 'normal' CHECK (role IN ('admin', 'normal')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_idx
  ON users (lower(username));
