CREATE TABLE IF NOT EXISTS collections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) > 0 AND length(name) <= 200),
  description text NOT NULL DEFAULT '' CHECK (length(description) <= 2000),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO collections (name, description)
SELECT 'Getting Started', 'Learn the basics of drawing with Blockly.'
WHERE NOT EXISTS (SELECT 1 FROM collections);

ALTER TABLE levels
  ADD COLUMN IF NOT EXISTS collection_id integer;

UPDATE levels
SET collection_id = (SELECT min(id) FROM collections)
WHERE collection_id IS NULL;

ALTER TABLE levels
  ALTER COLUMN collection_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'levels_collection_id_fkey'
  ) THEN
    ALTER TABLE levels
      ADD CONSTRAINT levels_collection_id_fkey
      FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS levels_collection_sort_order_idx
  ON levels (collection_id, sort_order);
