import * as Blockly from 'blockly/core';

const COLOR_ENTRIES = [
  ['red', '#ff0000'],
  ['green', '#00ff00'],
  ['blue', '#0000ff'],
  ['yellow', '#ffff00'],
  ['orange', '#ffa500'],
  ['purple', '#800080'],
  ['black', '#000000'],
  ['white', '#ffffff'],
];

const colorOptions = (labels) => COLOR_ENTRIES.map(([key, value]) => [labels.colors[key], value]);

export const getCustomBlocks = (labels) => Blockly.common.createBlockDefinitionsFromJsonArray([
  {
    type: 'call_moveUp',
    message0: labels.moveUp,
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: labels.moveUpTooltip,
    helpUrl: '',
  },
  {
    type: 'call_moveDown',
    message0: labels.moveDown,
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: labels.moveDownTooltip,
    helpUrl: '',
  },
  {
    type: 'call_moveLeft',
    message0: labels.moveLeft,
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: labels.moveLeftTooltip,
    helpUrl: '',
  },
  {
    type: 'call_moveRight',
    message0: labels.moveRight,
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: labels.moveRightTooltip,
    helpUrl: '',
  },
  {
    type: 'call_paint',
    message0: labels.paintWithColor,
    args0: [
      {
        type: 'field_dropdown',
        name: 'COLOR',
        options: colorOptions(labels),
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: labels.paintWithColorTooltip,
    helpUrl: '',
  },
  {
    type: 'call_eraseColor',
    message0: labels.eraseColor,
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: labels.eraseColorTooltip,
    helpUrl: '',
  },
  {
    type: 'get_current_color',
    message0: labels.getCurrentColor,
    output: 'String',
    colour: 160,
    tooltip: labels.getCurrentColorTooltip,
    helpUrl: '',
  },
  {
    type: 'call_setStartingRow',
    message0: labels.setStartingRow,
    args0: [
      {
        type: 'field_number',
        name: 'STARTING_ROW',
        value: 0,
        min: 0,
        max: 19,
        precision: 1,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: labels.setStartingRowTooltip,
    helpUrl: '',
  },
  {
    type: 'call_setStartingCol',
    message0: labels.setStartingCol,
    args0: [
      {
        type: 'field_number',
        name: 'STARTING_COL',
        value: 0,
        min: 0,
        max: 19,
        precision: 1,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: labels.setStartingColTooltip,
    helpUrl: '',
  },
  {
    type: 'color_value',
    message0: labels.colorValue,
    args0: [
      {
        type: 'field_dropdown',
        name: 'COLOR',
        options: colorOptions(labels),
      },
    ],
    output: 'String',
    colour: 160,
    tooltip: labels.colorValueTooltip,
    helpUrl: '',
  },
  {
    type: 'call_paint_with_param',
    message0: labels.paintWithParam,
    args0: [
      {
        type: 'input_value',
        name: 'COLOR',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: labels.paintWithParamTooltip,
    helpUrl: '',
  },
  {
    type: 'is_current_cell_painted',
    message0: labels.isCurrentCellPainted,
    colour: 160,
    tooltip: labels.isCurrentCellPaintedTooltip,
    helpUrl: '',
    output: 'Boolean',
  },
  {
    type: 'get_current_column',
    message0: labels.getCurrentColumn,
    colour: 160,
    tooltip: labels.getCurrentColumnTooltip,
    helpUrl: '',
    output: 'Number',
  },
  {
    type: 'get_current_row',
    message0: labels.getCurrentRow,
    colour: 160,
    tooltip: labels.getCurrentRowTooltip,
    helpUrl: '',
    output: 'Number',
  },
]);
